### ISSUE TITLE
update home page support content 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [biodivportal/ontoportal_web_ui#15]
Need to update this https://github.com/biodivportal/ontoportal_configs/blob/master/ui/bioportal_config_appliance.rb#L286

Require a png and a link

**Comment by naouelkaram** [comment]
{
      img_src: 'logos/supports/NFDI_4_Biodiversity_Logo.png',
      url: 'https://www.nfdi4biodiversity.org/en',
      target: '_blank',
    },
    {
      img_src: 'logos/supports/dfg_logo_schriftzug_blau_foerderung_en.jpg',
      url: 'https://www.dfg.de/en',
      target: '_blank',
    },
    {
      img_src: 'logos/collaboration/InfAI-Logo-mobile-sm.png',
      url: 'https://infai.org/',
      target: '_blank',
    }
    {
      img_src: 'logos/collaboration/ontoportal.png',
      url: 'https://ontoportal.org/',
      target: '_blank',
    }
![NFDI_4_Biodiversity_Logo](https://github.com/user-attachments/assets/43be8f53-7ebd-450f-a3f0-902718a232b9)
![dfg_logo_schriftzug_blau_foerderung_en](https://github.com/user-attachments/assets/e38b6ff7-63c8-4fc9-9dfe-a2ce00b504fb)
![InfAI-Logo-mobile-sm](https://github.com/user-attachments/assets/fae80b78-7cf4-4e20-844f-48a23391f12a)

**Comment by naouelkaram** [comment]
@syphax-bouazzouni please put the files in the right repo or let me know where to save them

**Comment by naouelkaram** [comment]
In $PORTALS_INSTANCES BiodivPortal should appear first then alphabetical order

**Comment by syphax-bouazzouni** [comment]
> In $PORTALS_INSTANCES BiodivPortal should appear first then alphabetical order

Done in https://github.com/biodivportal/ontoportal_configs/commit/96d98c0a0744086e29bb56c156907fbfbbd391e8
![image](https://github.com/user-attachments/assets/136b5a3e-5e55-40a0-b694-23b6ebedbefa)
