### ISSUE TITLE
sort in the homepage by size (classes + indivuduals) not by visits 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [biodivportal/ontoportal_web_ui#16]

**Comment by syphax-bouazzouni** [comment]
Done https://github.com/biodivportal/ontoportal_web_ui/commit/1ac694db4f1668f73c97bbd20f3662284bcabe21
![image](https://github.com/user-attachments/assets/8b7ffb9c-7735-4a76-817c-1277a5c20c8f)

**Comment by naouelkaram** [comment]
Call classes + instances  = terms
