### ISSUE TITLE
add an about page 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [biodivportal/ontoportal_web_ui#18]
like https://terminologies.gfbio.org/about/ 
and https://ecoportal.lifewatch.eu/about

**Comment by syphax-bouazzouni** [comment]
@naouelkaram here I will need to the content to put in the page. 
I will need in English:

- About text
- Teams members and description 
- How to cite us?
- Partners logos and links

**Comment by naouelkaram** [comment]
[InputAboutPage.txt](https://github.com/user-attachments/files/16907771/InputAboutPage.txt)
Logos downloaded from https://www.nfdi4biodiversity.org/de/wer-wir-sind/#d46dea28-40b8-41cd-9c61-8e7dbc4b0a9b
Logos not clickable
![BLACK-PNG original_ANo7SjT](https://github.com/user-attachments/assets/a69be6c3-0736-403a-b23b-c45f859464e1)
![Logo-final_bw original](https://github.com/user-attachments/assets/4ddf15ee-b52b-48c0-ab3f-0d38ba66f403)
![FBN_Logo_Bildmarke_RGB_black original](https://github.com/user-attachments/assets/acac6f72-8137-44d5-9d89-5c2a53b76f37)
![GFBio_Logo_Positiv original_QmZUE6D](https://github.com/user-attachments/assets/27fb182b-d0bb-442f-add5-0cc239ab20d6)
![UniMarburg_Logo_Positiv original_s1OaZKW](https://github.com/user-attachments/assets/d818a6ff-2a1b-4b4a-986c-392072aaf54e)
![Uni_Jena_Logo_Positiv original_FdIMbop](https://github.com/user-attachments/assets/a66f3ce5-b40a-4313-88dc-264343e52be0)
![Bo_Logo-big-online_RGB-black original_3Rmk5xf](https://github.com/user-attachments/assets/2abfd055-ec2e-41a9-8494-a8e941903dfe)
![SNSB_Logo_Positiv original_SCzTJS5](https://github.com/user-attachments/assets/2edaf9e5-dfc6-4584-953f-c947d17a2a01)

**Comment by naouelkaram** [comment]
@syphax-bouazzouni  in the citation accessed should display the current date (today)

**Comment by syphax-bouazzouni** [comment]
done in 4a773d27f5a0f4a482e8b50718237ef4d91a08fa
![image](https://github.com/user-attachments/assets/0b4808fd-727a-468e-94b1-0d1dd46a2dce)
