### ISSUE TITLE
Split the submitted part and the contact part in Browse page

### ISSUE THREAD

**Issue by naouelkaram** [biodivportal/ontoportal_web_ui#21]
Separate the submitted part from the contact part using the text from the ontology page in Mouse Hover
![grafik](https://github.com/user-attachments/assets/3b84f2b2-6cfb-4842-a6f1-f2f8b88efea9)

**Comment by syphax-bouazzouni** [comment]
Done 
![image](https://github.com/user-attachments/assets/41229e72-e3f4-4b8a-865b-e96798b5b908)
