### ISSUE TITLE
ERROR_RDF for SWO

### ISSUE THREAD

**Issue by naouelkaram** [biodivportal/ontoportal_web_ui#32]
The submission of the SWO did not work, The ontology is not accessible
![grafik](https://github.com/user-attachments/assets/1faee397-6e50-4c26-b5f9-ebbc094392cf)

**Comment by syphax-bouazzouni** [comment]
It seems the file is not correct, when trying to open it using Protege we get more details of the parsing error
![image](https://github.com/user-attachments/assets/991dfa43-30e5-4228-8d59-848de799d5bf)

**Comment by syphax-bouazzouni** [comment]
The issue was in the pull location, changed from https://github.com/allysonlister/swo/blob/master/swo-full.owl, which returns an HTML page, into https://raw.githubusercontent.com/allysonlister/swo/refs/heads/master/swo-full.owl which is the correct file.

**Comment by syphax-bouazzouni** [comment]
Fixed https://biodivportal.gfbio.org/ontologies/SWO
![image](https://github.com/user-attachments/assets/cf513c1e-139c-4450-bd8c-5a9053436b2c)
