### ISSUE TITLE
change the text using the gfbio home page text 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [biodivportal/ontoportal_web_ui#7]

**Comment by syphax-bouazzouni** [comment]
add buttons in the home page to simulate the the buttons of gfbio

**Comment by syphax-bouazzouni** [comment]
make the button access redirect to https://data.biodivportal.gfbio.dev/documentation

**Comment by naouelkaram** [comment]
Let us keep only the submit and discover button for now
